name: CCTV Update Notify Dev
on:
  push:
    branches: [ dev ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: CCTV Update Notify Dev
        uses: fjogeleit/http-request-action@v1
        with:
          url: ${{ secrets.WEBHOOK_URL_DEV }}
          method: 'POST'
          data: '{embeds:[{title:"Testing", description:"Testing $GITHUB_SHA"}]}'